name: photoeditor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  gallery_saver_plus: ^3.2.9

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # --- ADDED THIS SECTION ---
  # Make sure 'assets:' is indented with two spaces
  assets:
    - assets/textures/
  # -------------------------